version: '3'
services:
  backend:
    env_file:
      - ./.env
    build: ./backend_app
    image: backend-app
    environment:
      - BACKEND_IP=$BACKEND_IP
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    networks:
      - frontend_backend_network

networks:
  frontend_backend_network:
    driver: bridge
